name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
        # Add this line below to tell Ruby where your Gemfile is
        working-directory: ./your-folder-name 

      - name: Build Jekyll Site
        # Add this line below to tell Jekyll where your config file is
        working-directory: ./your-folder-name
        run: bundle exec jekyll build
